version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  # Uncomment if you need a database
  # database:
  #   image: postgres:15-alpine
  #   container_name: nestjs-db
  #   environment:
  #     POSTGRES_DB: nestjs_db
  #     POSTGRES_USER: nestjs_user
  #     POSTGRES_PASSWORD: nestjs_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# volumes:
#   postgres_data:
